### PR TITLE
Change to only use parMapN for configuration

### PR DESCRIPTION
**Pull request by vlovgr**
No need for `flatMap` here, and so we can see all configuration errors at once. :)

### CODE REVIEW

**Comment by kubukoz** [comment]
I think the reason to have this intermediate step was to be able to look at all the differences between environments in one place (instead of looking for all the pattern matches, which there will be many of if you have more variables that differ) but I don't know, maybe @gvolpe will like it ;)

**Comment by vlovgr** [comment]
If you really want that (I've personally not found that I've needed it), then you can move those values to the start of the `parMapN` block. Multiple matches, but at least they're closer together. Only benefit here is error accumulation, so no huge gains.

**Comment by gvolpe** [comment]
Hi @vlovgr ! Thanks for taking the time to look into this.

@kubukoz's comment is on point. I prefer to perform the pattern matching in a single place to easily identify the difference between the environments.

Error accumulation is a good selling point but in this case we have that except for the first environment variable `SC_APP_ENV` right?

In the end, I guess it's just a matter of preference and style, and I prefer what we currently have :)

**Comment by vlovgr** [comment]
It's definitely a matter of preference. It also shows there's a need for something between `Applicative` and `FlatMap`, because `flatMap` is essentially a too powerful construct here (it allows you to have completely different configuration loading across environments). Will be interesting to see how `Selective` turns out. :)

**Pull request closed without merging**
